services:
  - type: web
    name: Asafor-frontend
    env: node
    rootDirectory: web/frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
  - type: web
    name: Asafor-admin
    env: node
    rootDirectory: web/admin
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true

